<?php

namespace Container7h2hegJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D2rBjWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D2r_bjW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D2r_bjW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pricingPlanRepository' => ['privates', '.errored.HeM0VZk', NULL, 'Cannot determine controller argument for "App\\Controller\\MenuController::index()": the $pricingPlanRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\PricingPlanRepository". Did you forget to add a use statement?'],
        ], [
            'pricingPlanRepository' => '?',
        ]);
    }
}
