<?php

namespace Container7h2hegJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_HeM0VZkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.HeM0VZk' shared service.
     *
     * @return \App\Controller\PricingPlanRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\MenuController::index()": the $pricingPlanRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\PricingPlanRepository". Did you forget to add a use statement?');
    }
}
