<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGntWt9P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGntWt9P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGntWt9P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGntWt9P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGntWt9P\App_KernelDevDebugContainer([
    'container.build_hash' => 'GntWt9P',
    'container.build_id' => 'fffefa00',
    'container.build_time' => 1738848188,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGntWt9P');
