<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZfnjQj2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZfnjQj2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZfnjQj2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZfnjQj2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZfnjQj2\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZfnjQj2',
    'container.build_id' => '8394a345',
    'container.build_time' => 1736950128,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZfnjQj2');
